### ISSUE TITLE
Very good work, can you please make the model weights open source? We hope to do a verification.

### ISSUE THREAD

**Issue by YUANMU227** [woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC#4]
Very good work, can you please make the model weights open source? We hope to do a verification.

**Comment by woshidandan** [comment]
Download weights from here: https://drive.google.com/drive/folders/1KMRWBXFRx74IMaidMhpAeDfeq6h3g3UV

**Comment by YUANMU227** [comment]
Thank you for sharing. How can I export the model to my local computer after downloading it in the web interface?

**Comment by YUANMU227** [comment]
Hello, what is the difference between these two models?
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/c19a0f81-ca73-4167-88a8-e99060d6bae8)

There is another running script in this document. What is the difference between it and the script in the original warehouse?
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/ee63cbbc-e25e-44e6-8140-008c5eea3ab4)

**Comment by woshidandan** [comment]
> Hello, what is the difference between these two models? ![image](https://private-user-images.githubusercontent.com/50391329/340204364-c19a0f81-ca73-4167-88a8-e99060d6bae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDc0MzUsIm5iZiI6MTcxODYwNzEzNSwicGF0aCI6Ii81MDM5MTMyOS8zNDAyMDQzNjQtYzE5YTBmODEtY2E3My00MTY3LTg4YTgtZTk5MDYwZDZiYWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2NTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMTBiOTQ1NTZhNzRlOTQ1ODRiZWViMDJjNDJiMjFkMTQ2ZmJiNDE5MGJmZjllZmNlN2QzZTZlMWE0NGUxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iZwgeS4nSqmW2UOViVc2L-djHsexfGKpAg1vzFd38W4)
> 
> There is another running script in this document. What is the difference between it and the script in the original warehouse? ![image](https://private-user-images.githubusercontent.com/50391329/340204246-ee63cbbc-e25e-44e6-8140-008c5eea3ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDc0MzUsIm5iZiI6MTcxODYwNzEzNSwicGF0aCI6Ii81MDM5MTMyOS8zNDAyMDQyNDYtZWU2M2NiYmMtZTI1ZS00NGU2LTgxNDAtMDA4YzVlZWEzYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2NTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzNkOTI0NWU4NzZmNTk1YzQ1MGE3ZDU2Y2MyZGNkZDRiYWI0MzJmNDkzNGQ3MDNiMjRmZDRjODgwYTliOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.37pA7KbU7fkNkLUsXU63UcBsZISl0xSHr6OqvmXIzJk)

There is no difference, this is the code and weights we submit to CVPRW, the weights and codes are the same and can be used with each other.

**Comment by YUANMU227** [comment]
OK, thank you very much. I will try to test it.

**Comment by YUANMU227** [comment]
Hello, I used the AIGC_DB_AIGCQA30K_TEST.py file in the github repository and the AIGC_DB_prompt_final.py in the url download link you shared, and the results on the test set are different:
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/4af0916c-622d-4273-a5b4-8a8ca380f8e3)
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/ffcde76e-154b-40cf-856e-fa2b94020749)

Looking at the code, I found that AIGC_DB_prompt_final.py uses the above two models at the same time and merges the results of the two models. What is the purpose of this? What is the difference between the two reasoning methods and the two models? Which of the two reasoning methods is more accurate?
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/fbfcfb70-f37f-4b28-b46d-053ccf9c1773)
![image](https://github.com/woshidandan/Champion-Solution-for-CVPR-NTIRE-2024-Quality-Assessment-on-AIGC/assets/50391329/e242b6aa-9930-4c0e-9578-b98b31e89656)

**Comment by woshidandan** [comment]
If you train from scratch, I recommend using the code in the GitHub repository because it is good to reproduce; if you are looking for high performance and don't require retraining, I recommend using the code in the link I provided because a lot of Trick is used. in short, it is recommended to use the code in the link, and I will modify the code in the repository later to prevent confusion.
